// Import keys generated by 'npx @veramo/cli config create-secret-key'
import { NAV_KMS_SECRET_KEY, SYMFONI_KMS_SECRET_KEY, USER_KMS_SECRET_KEY, INFURA_PROJECT_ID } from '../../keys'

// Core interfaces
import { createAgent, IDIDManager, IResolver, IDataStore, IKeyManager } from '@veramo/core'

// Core identity manager plugin
import { DIDManager } from '@veramo/did-manager'

// Ethr did identity provider
import { EthrDIDProvider } from '@veramo/did-provider-ethr'

// Web did identity provider
import { WebDIDProvider } from '@veramo/did-provider-web'

// Core key manager plugin
import { KeyManager } from '@veramo/key-manager'

// Custom key management system for RN
import { KeyManagementSystem, SecretBox } from '@veramo/kms-local'

// Custom resolvers
import { DIDResolverPlugin } from '@veramo/did-resolver'
import { Resolver } from 'did-resolver'
import { getResolver as ethrDidResolver } from 'ethr-did-resolver'
import { getResolver as webDidResolver } from 'web-did-resolver'

// Storage plugin using TypeOrm
import { Entities, KeyStore, DIDStore, IDataStoreORM, PrivateKeyStore, migrations } from '@veramo/data-store'

// TypeORM is installed with `@veramo/data-store`
import { createConnection } from 'typeorm'

// Local sqlite database for the different agents
const NAV_DATABASE_FILE = 'nav-database.sqlite'
const SYMFONI_DATABASE_FILE = 'symfoni-database.sqlite'
const USER_DATABASE_FILE = 'user-database.sqlite'

// You will need to get a project ID from infura https://www.infura.io
const INFURA_ID = INFURA_PROJECT_ID

const NAV_KEY = NAV_KMS_SECRET_KEY
const SYMFONI_KEY = SYMFONI_KMS_SECRET_KEY
const USER_KEY = USER_KMS_SECRET_KEY
